# Generated by Django 3.1.3 on 2020-11-20 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ikincidil', '0002_auto_20201120_1518'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='setting',
            name='about_name',
        ),
        migrations.AddField(
            model_name='about',
            name='main_title',
            field=models.CharField(default=1, max_length=150, verbose_name='Hakkımızda başlığı'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='about',
            name='one_header',
            field=models.BooleanField(default=False, verbose_name='Tek başına About tipinde başlık eklemek istiyorsanız tıklayınız.'),
        ),
        migrations.AddField(
            model_name='resume',
            name='date',
            field=models.CharField(default='First Day', max_length=100, verbose_name='Tarih kısmı'),
        ),
        migrations.AddField(
            model_name='resume',
            name='left',
            field=models.BooleanField(default=True, verbose_name='Sol tarafta gözükmesini istiyorsanız tıklayınız.'),
        ),
        migrations.AddField(
            model_name='service',
            name='link',
            field=models.BooleanField(default=False, verbose_name='detay sayfasının açılmasını istiyorsanız tıklayınız: '),
        ),
        migrations.AddField(
            model_name='setting',
            name='media_name',
            field=models.CharField(default='All', max_length=20, verbose_name='Media kısmında hepsi'),
        ),
        migrations.AlterField(
            model_name='aboutlogo',
            name='font',
            field=models.CharField(default='icofont-jail', max_length=80),
        ),
        migrations.AlterField(
            model_name='resume',
            name='ranking',
            field=models.SmallIntegerField(verbose_name='sıralama sayısı'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='sub1_title',
            field=models.CharField(max_length=100, verbose_name='Yeşil renkli başlık'),
        ),
    ]
