# Generated by Django 3.1.3 on 2020-11-20 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ikincidil', '0003_auto_20201120_1951'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='activation',
            field=models.BooleanField(default=True, verbose_name='Türkçe web sitesinin açılması için tıklayınız'),
        ),
    ]
