# Generated by Django 3.1.3 on 2020-11-20 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ikincidil', '0004_setting_activation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setting',
            name='activation',
            field=models.BooleanField(default=False, verbose_name='Türkçe web sitesinin açılması için tıklayınız'),
        ),
    ]
