# Generated by Django 3.1.3 on 2020-11-16 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_service'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='service',
            options={'verbose_name': 'Hizmet', 'verbose_name_plural': 'Hizmetler'},
        ),
        migrations.AlterField(
            model_name='service',
            name='content',
            field=models.CharField(max_length=50, verbose_name='İçerik'),
        ),
    ]
