# Generated by Django 3.1.3 on 2020-11-16 16:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20201116_1921'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=10, verbose_name='Şirket tipi')),
            ],
            options={
                'verbose_name': 'Şirket Tipi',
                'verbose_name_plural': 'Şirket Tipleri',
            },
        ),
        migrations.CreateModel(
            name='Reference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Referansın adı:')),
                ('content', models.CharField(max_length=75, verbose_name='Referansın kısa açıklaması:')),
                ('image', models.ImageField(upload_to='', verbose_name='Referans resmi')),
                ('company_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.companytype')),
            ],
            options={
                'verbose_name': 'Referans',
                'verbose_name_plural': 'Referanslar',
            },
        ),
    ]
