# Generated by Django 3.1.3 on 2020-11-17 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20201117_2005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setting',
            name='contact_name',
            field=models.CharField(default='Contact', max_length=20, verbose_name='Başlık6'),
        ),
    ]
