# Generated by Django 3.1.3 on 2020-11-17 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20201117_2007'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='contact_adress_name',
            field=models.CharField(default='Adresse', max_length=20, verbose_name='Contact kısmındaki mail başlığı'),
        ),
        migrations.AddField(
            model_name='setting',
            name='contact_mail_name',
            field=models.CharField(default='Email', max_length=20, verbose_name='Contact kısmındaki mail başlığı'),
        ),
        migrations.AddField(
            model_name='setting',
            name='contact_social_name',
            field=models.CharField(default='Social Media', max_length=20, verbose_name='Contact kısmındaki sosyal adres başlığı'),
        ),
        migrations.AddField(
            model_name='setting',
            name='contact_sub_name',
            field=models.CharField(default='Contact with us', max_length=20, verbose_name='Contact kısmının alt başlığı'),
        ),
        migrations.AddField(
            model_name='setting',
            name='contact_tel_name',
            field=models.CharField(default='Tel', max_length=20, verbose_name='Contact kısmındaki telefon başlığı'),
        ),
    ]
