# Generated by Django 3.1.3 on 2020-11-17 20:10

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20201117_2023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='content',
            field=ckeditor.fields.RichTextField(verbose_name='içerik'),
        ),
    ]
