# Generated by Django 3.1.3 on 2020-11-17 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20201117_2310'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='detay sayfası için resim'),
        ),
    ]
