# Generated by Django 3.1.3 on 2020-11-17 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_auto_20201118_0038'),
    ]

    operations = [
        migrations.AddField(
            model_name='reference',
            name='youtube_url',
            field=models.URLField(default='https://www.youtube.com/watch?v=0luxaZqY1Qs', verbose_name='youtube_video_urli'),
            preserve_default=False,
        ),
    ]
