# Generated by Django 3.1.3 on 2020-11-18 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_auto_20201118_2315'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Bu bölümün yayınlanması için tıklayınız'),
        ),
    ]
