# Generated by Django 3.1.3 on 2020-11-20 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_auto_20201120_1254'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='companytype',
            options={'verbose_name': 'Portfolio Tipi', 'verbose_name_plural': 'Portfolio Tipleri'},
        ),
        migrations.AddField(
            model_name='setting',
            name='contact_from',
            field=models.CharField(default='Contact Form', max_length=20, verbose_name='Contact Form Başlığı'),
        ),
    ]
