# Generated by Django 3.1.3 on 2020-11-20 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_auto_20201120_1314'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='setting',
            name='contact_from_content',
        ),
        migrations.AlterField(
            model_name='setting',
            name='contact_form_url',
            field=models.URLField(default='https://www.google.com/', max_length=100, verbose_name='Contact Form Linki'),
        ),
    ]
