# Generated by Django 3.1.3 on 2020-11-20 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0024_auto_20201120_1333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reference',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Referans resmi'),
        ),
    ]
