# Generated by Django 3.1.3 on 2020-11-20 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0025_auto_20201120_1400'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resume',
            name='date',
        ),
    ]
