# Generated by Django 3.1.3 on 2020-11-20 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0026_remove_resume_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resume',
            name='sub_title',
        ),
    ]
