# Generated by Django 3.1.3 on 2020-11-20 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0027_remove_resume_sub_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='main_title',
            field=models.CharField(default='elma', max_length=150, verbose_name='Hakkımızda başlığı'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='about',
            name='one_header',
            field=models.BooleanField(default=False, verbose_name='Tek başına About tipinde başlık eklemek istiyorsanız tıklayınız.'),
        ),
    ]
