# Generated by Django 3.1.3 on 2020-11-20 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0028_auto_20201120_1755'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='setting',
            name='about_name',
        ),
    ]
