# Generated by Django 3.1.3 on 2020-11-20 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0029_remove_setting_about_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutlogo',
            name='font',
            field=models.CharField(max_length=80),
        ),
    ]
