# Generated by Django 3.1.3 on 2020-11-20 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0030_auto_20201120_1818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutlogo',
            name='font',
            field=models.CharField(default='icofont-jail', max_length=80),
        ),
    ]
