# Generated by Django 3.1.3 on 2020-11-20 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0031_auto_20201120_1819'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='date',
            field=models.CharField(default='First Day', max_length=100, verbose_name='Tarih kısmı'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='sub1_title',
            field=models.CharField(max_length=100, verbose_name='Yeşil renkli başlık'),
        ),
    ]
