# Generated by Django 3.1.3 on 2020-11-20 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0032_auto_20201120_1820'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='left',
            field=models.BooleanField(default=True),
        ),
    ]
