# Generated by Django 3.1.3 on 2020-11-20 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0033_resume_left'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='ranking',
            field=models.SmallIntegerField(verbose_name='sıralama sayısı'),
        ),
    ]
