# Generated by Django 3.1.3 on 2020-11-20 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0035_auto_20201120_1915'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='link',
            field=models.BooleanField(default=False, verbose_name='detay sayfasının açılmasını istiyorsanız tıklayınız: '),
        ),
    ]
