# Generated by Django 3.1.3 on 2020-11-20 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0036_service_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='media_name',
            field=models.CharField(default='All', max_length=20, verbose_name='Media kısmında hepsi'),
        ),
    ]
