# Generated by Django 3.1.3 on 2020-11-22 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0037_setting_media_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reference',
            name='image',
            field=models.ImageField(default=1, upload_to='', verbose_name='Referans resmi'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='service',
            name='image',
            field=models.ImageField(default=1, upload_to='', verbose_name='detay sayfası için resim'),
            preserve_default=False,
        ),
    ]
